### ISSUE TITLE
Support generator map and flatMap

### ISSUE THREAD

**Issue by hmvien** [pholser/junit-quickcheck#100]
Hey! I really appreciate your work on this project. One functionality that I really miss from ScalaCheck is the ability to expressively chain series of transformation function to existing Generator in order to build another Generator of a different type. This allows test code to be more DRY.

Proposal:
Add map and flatMap to the Generator interface with these signatures
`<A, B> Generator<B> map(Function<A, B> f)`
`<A, B> Generator<B> flatMap(Function<A, Generator<B>> f)` 

Use cases:
```
// With map
Generator<Int> intGen = ....;
Generator<String> stringGen = intGen.map(v -> v.toString());

// With flatmap with Java8 syntax
Generator<Double> latitudeGen = ....;
Generator<Double> longitudeGen = ....;
Generator<Coordinate> coordinateGen = latitudeGen.flatMap(latitude -> {
  return longitudeGen.map(longitude -> {
     return new Coordinate(latitude, longitude);
  });
});
```

**Comment by pholser** [comment]
@hmvien Thanks for your interest! I agree, creating and composing generators is a bit clunky at present. `map` and `flatMap` seem like they would help. That, combined with the ability in the 0.7 snapshots for a generator to call methods on the result of `gen()` to access generators that can produces values of specific types, hopefully will be even more helpful.

**Comment by Muzietto** [comment]
:+1:

**Comment by pholser** [comment]
@hmvien Would you mind to have a look at branch issues/100/map-and-flatmap ? I've extracted functional interface `Gen`, with single abstract method `generate`, and default methods `map` and `flatMap`. `map` and `flatMap`, in combination with the `gen()` method of `Generator`, hopefully will make creating generators for custom types (ServiceLoader-provided or otherwise) smoother.

Let me know! Thanks for your constructive feedback.

**Comment by hmvien** [comment]
This is awesome! Everything looks good from my end. Really appreciate you quickly implementing this functionality!
