### ISSUE TITLE
Constrain the length of a string

### ISSUE THREAD

**Issue by jeremyheiler** [pholser/junit-quickcheck#149]
I have a method that effectively calls `String.charAt()`, so I want to generate random strings and random indexes. Currently, I am using `@InRange` on the index parameter with a min of 0, and a max based on empirical observations of the lengths of the strings being generated. I also have assumptions that restrict the index to be within the bounds of the string. (Without setting a max on the index, none of the samples would ever be asserted.) Is there a better way to do this?

**Comment by pholser** [comment]
@jeremyheiler Thanks for your interest in junit-quickcheck!

One way to guarantee the generation of the two parameters obeys the constraint is to create a type that encompasses the two parameters, and make a generator for that type. Then your properties accept one parameter of that type, rather than two parameters of types `String` and `int`, respectively.

```java
@RunWith(JUnitQuickcheck.class)
public class StringIndexingProperties {
    public static class StringAndIndex {
        final String s;
        final int index;

        public StringAndIndex(String s, int index) {
            assert index >= 0 && index < s.length();
            this.s = s;
            this.index = index;
        }
    }

    public static class StringAddr extends Generator<StringAndIndex> {
        public StringAddr() {
            super(StringAndIndex.class);
        }

        @Override public StringAndIndex generate(
            SourceOfRandomness r,
            GenerationStatus s) {

            String string = gen().type(String.class).generate(r, s);
            return new StringAndIndex(
                string,
                r.nextInt(string.length());
        }
    }

    @Property public void x(@From(StringAddr.class) StringAndIndex si) {
        si.s.charAt(si.i);

        // ...
    }
}
```

You can tidy this up a bit by making `StringAddr` available to the Java `ServiceLoader`; then you won't have to mark your property parameter with `@From(...)`. See [Implied Generators via ServiceLoader](http://pholser.github.io/junit-quickcheck/site/0.7/usage/other-types.html) for more on that.

It may be more straightforward to do what you're already doing -- two parameters of type `String` and `@InRange(minInt = 0, maxInt = ...) int`, with an assumption to weed out non-compliers. Do consider creating a type to represent the data you want, with constraints.

**Comment by jeremyheiler** [comment]
Thank you, @pholser! That worked perfectly. I'm slowly getting the hang of this :-)
