### ISSUE TITLE
@InRange does not support primitive types

### ISSUE THREAD

**Issue by TomDmitriev** [pholser/junit-quickcheck#56]
I don't understand why `@InRange` doesn't support primitive values any more. Sometimes I need to use primitive values already defined as constants like

     ForAll @InRange(minInt = PasswordMatcher.MIN, maxInt = PasswordMatcher.MIN) int stringSize

There's no way I can reuse those constants, which is frustrating.

**Comment by pholser** [comment]
@TomDmitriev I had taken them out to thin out the `InRange` API; and because one might get surprising results using `min{primitive}` with theory parameters of type `Number`. On second thought, the likelihood of this kind of confusion appears smaller than the inconvenience of not having the extra attributes of `InRange`. I'll add them back. Sorry for the trouble!

**Comment by pholser** [comment]
@TomDmitriev Latest snapshot on oss.sonatype.org should have the `min{Primitive}` attributes of `InRange` back in place.
