### ISSUE TITLE
How to generate a list of custom objects

### ISSUE THREAD

**Issue by TomDmitriev** [pholser/junit-quickcheck#57]
I'm having hard time trying to generate a list of objects. Here's my parameter.

    @ForAll(sampleSize = 5) @From(RoleGenerator.class) List<Role> roles

I've tried to make RoleGenerator produce objects of type Role, I've also tried to make it produce lists of such objects but neither have worked. Am I missing something or such a feature isn't implemented yet? In any case, I think, it'd be nice if the following was possible:

    @ForAll(sampleSize = 5) List<@From(RoleGenerator.class) Role> roles

**Comment by pholser** [comment]
@TomDmitriev Agreed that using `@From` on type uses is desirable. I logged an issue to that effect a while back; haven't gotten around to implementing it.

In the meantime, try packaging your generator in a ServiceLoader JAR and putting it on the class path? It should get picked up.

**Comment by ieure** [comment]
Just adding that I also ran into this. Ideally I'd like to see clearly documented ways to:

 - Compose sequences from existing generators, both instances and classes.
 - Specify min/max number of elements in the sequence (distinct from min/max bounds for elements contained inside)

The main issue right now seems to be that `Generator`'s constructor needs the `Class` of the thing to be generated, but you can't represent a parameterized type in a `Class`. I was eventually able to work around this by making a `MyTypeGenerator<List>`, ignoring the type params entirely, and casting in the test itself (gross).

The min/max elements is also an issue, as `CollectionGenerator` has no way to tune the size of generated collections. So for example, a test with `assumeThat(theList.size(), greaterThan(1));` seems to fail, as the first two elements don't meet the assumption and JUQC flips over into `Zilch` generation mode. I thought perhaps `@InRange` would work to control array size bounds, but it has no effect.

**Comment by TomDmitriev** [comment]
I believe it is possible to control the size of a collection by applying to it something like `@ForAll(suchThat = "#_.size() > 1")`

**Comment by pholser** [comment]
@ieure, @TomDmitriev Thanks for your feedback!

Here are some ways you can constrain a theory over collections to apply only for values of a certain size:

* As @TomDmitriev mentions, use a constraint expression on the collection theory parameter
* Use an assumption:

        assumeThat(items.size(), lessThan(4));

* Create a generator for, say, `List` that uses a configuration annotation to communicate the desired size range:

        @Target({PARAMETER, FIELD, ANNOTATION_TYPE, TYPE_USE})
        @Retention(RUNTIME)
        @GeneratorConfiguration
        public @interface Sized {
            int min() default 0;
            int max() default 0;
        }

        public class SizedArrayListGenerator extends ArrayListGenerator {
            public void configure(Sized sized) {
                // stash/negotiate min/max size
            }

            @Override public ArrayList<?> generate(random, status) {
                ArrayList<Object> items = empty();
                int numberOfItems = random.nextInt(minSize, maxSize);
                for (int i = 0; i < numberOfItems; ++i)
                    items.add(componentGenerators().get(0).generate(random, status));
                return items;
            }
        }

    Then, use `@From` or package your generator in a ServiceLoader JAR and place it on the classpath.

It sounds as though it might be useful to have the baked-in collections generators support a min/max size configuration annotation. That sounds like a separate issue from this one, which, if I'm understanding correctly, is: if I want a theory parameter whose type is, say, `List<Foo>`, where I control `Foo`, how do I make junit-quickcheck recognize my `FooGenerator`? If `FooGenerator` is in a ServiceLoader JAR on the classpath, junit-quickcheck should pick up the `FooGenerator` and produce a `List<Foo>` as normal. If I want to use `@From` instead:

    @Theory public void x(@ForAll List<@From(FooGenerator.class) Foo> foos) {
        // ...
    }

then the resolution for #45 should enable the use of `@From` on type uses.

I agree that junit-quickcheck needs some better documentation regarding how to work custom types into the mix. I will consider how better to communicate this. Do you have any suggestions?

**Comment by pholser** [comment]
@TomDmitriev @ieure I have a question about this request.

To enable the construction:

    @Theory public void x(@ForAll List<@From(FooG.class) Foo> foos) {
    }

We would give the `@From` annotation an additional `@Target` value of `TYPE_USE`.

Now, it so happens that junit-quickcheck makes a good effort to support generic types not just with plain old type arguments such as `Integer` or `String`, but with wildcards also:

    @Theory public void x(@ForAll List<?> items)
    @Theory public void x(@ForAll List<? extends Number> items)
    @Theory public void x(@ForAll List<? super Integer> items)
    @Theory public void x(@ForAll Map<String, ?> items)
    @Theory public void x(@ForAll Map<? extends Number, ? super Integer> items)
    ...

Because `@From` would now have an additional target of `TYPE_USE`, this means that `@From` would be allowed on wildcards and their bounds. However, it doesn't seem like using `@From` on type parameters with wildcards makes a whole lots of sense. In the case of `List<?>`, if you really don't care what type of things the `List` holds, why mark it with a `@From`? And if you know the kinds of things your `@From` generator will produce, why not make the type of the theory parameter be `List<YourThing>`? Same goes for wildcards with bounds.

My question is this: if we go with allowing `@From` on type uses, are we OK with either ignoring `@From` annotations on wildcards with or without bounds, or with treating such markings as errors?

I appreciate your interest and feedback!

**Comment by TomDmitriev** [comment]
I'd be ok with either, however I wouldn't ignore them completely. If we
don't treat such markings as errors, we should probably at least produce a
warning message when we encounter one.

**Comment by pholser** [comment]
@TomDmitriev @ieure I have some prelim work on this on this branch: https://github.com/pholser/junit-quickcheck/tree/issue/45/from-on-type-uses

It passes all the tests, including the one mentioned in issue 45. There are a lot more tests to write, for sure, to ensure that the annotations on type uses influence the graph of generators for a parameter correctly. I wanted to publish the ongoing work and let you know, so that you can verify whether this will meet your needs.

Thanks again!

**Comment by pholser** [comment]
Added issues #59, #60, and #61 for enhancing built-in array, collection, and map generators with the ability to constrain the size/length of generated aggregates.

**Comment by pholser** [comment]
@TomDmitriev @ieure I've gone ahead and merged this feature branch on to master. Have a look when you have a moment, and let me know what you think. Thanks!
