### ISSUE TITLE
Default seed

### ISSUE THREAD

**Issue by karlicoss** [pholser/junit-quickcheck#96]
As far as I understand from [here](https://github.com/pholser/junit-quickcheck/blob/224411c548d047ffaa2be28f55a54e57d3192170/core/src/main/java/com/pholser/junit/quickcheck/internal/generator/PropertyParameterGenerationContext.java#L71), if I don't specify seed via `When` annotation, the generator relies on the default seed of the `java.util.Random` class, which is not deterministic and might change depending on external conditions (for instance, as for Android, default seed is chosen as `this(seedUniquifier() ^ System.nanoTime())`).

Is there any reason we just don't always initialize the source of randomness with the default seed `0` (unless another seed is specified) ? One issue I see here is if we have, for instance, two integers as the input for test, they will correlate due to the same seed.

However, we could still make them uncorrelated yet deterministic if we, for instance, make default seed also dependent on parameter number (we can pass it from [here](https://github.com/pholser/junit-quickcheck/blob/master/core/src/main/java/com/pholser/junit/quickcheck/runner/PropertyStatement.java#L169)). That way the tests will always be reproducible, even with unspecified seed.

If you think it's a good idea, I would be happy to contribute :)

**Comment by pholser** [comment]
@karlicoss Thanks for your interest in junit-quickcheck!

Without any `@When(seed)` markings, each parameter of a property method has its values generated with its own source of randomness, each seeded uniquely. See `PropertyStatement.parameters(trials)`, and `SourceOfRandomness(Random)`.

If a property parameter is marked with `@When(seed != 0)`, then that seed will be used instead. Mostly this is intended to be used when a property fails for a particular set of inputs, and you want to be able to rerun the failed property against those inputs. See #51.

Generally speaking, I think it's important for junit-quickcheck to use different seeds every time a property is verified, because it affords us more opportunity to discover a failing case.
